name: Let's Release
description: 🚀 Let's release as soon as possible
author: TozyDev
branding:
  color: green
  icon: tag

inputs:
  version-format:
    description: |
      The format of the version to release.
      There are available placeholders:
        - major
        - minor
        - patch
        - YYYY
        - YY
        - 0Y
        - MM
        - 0M
        - WW
        - 0W
        - DD
        - 0D

    required: false
    default: major.minor.patch

outputs:
  release-type:
    description: The type of release (none, patch, minor, major)
    value: ${{ steps.get-release-type.outputs.type }}

  next-version:
    description: The next version to release
    value: ${{ steps.get-next-version.outputs.version }}

  major:
    description: The major part of the next version to release
    value: ${{ steps.parse-version-parts.outputs.major }}

  minor:
    description: The minor part of the next version to release
    value: ${{ steps.parse-version-parts.outputs.minor }}

  patch:
    description: The patch part of the next version to release
    value: ${{ steps.parse-version-parts.outputs.patch }}

  release-notes-md:
    description: The release notes file in markdown format
    value: ${{ steps.generate-release-notes.outputs.notes }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: get-release-type
      shell: bash
      run: echo "type=$("$GITHUB_ACTION_PATH"/scripts/get-release-type.sh "$VERSION_FORMAT")" >> $GITHUB_OUTPUT
      env:
        VERSION_FORMAT: ${{ inputs.version-format }}

    - id: get-next-version
      if: ${{ steps.get-release-type.outputs.type != 'none' }}
      shell: bash
      run: echo "version=$("$GITHUB_ACTION_PATH"/scripts/get-next-version.sh "$RELEASE_TYPE" "$VERSION_FORMAT")" >> $GITHUB_OUTPUT
      env:
        RELEASE_TYPE: ${{ steps.get-release-type.outputs.type }}
        VERSION_FORMAT: ${{ inputs.version-format }}

    - id: parse-version-parts
      if: ${{ steps.get-release-type.outputs.type != 'none' }}
      shell: bash
      run: |
        echo "major=$("$GITHUB_ACTION_PATH"/scripts/get-version-part.sh "$NEXT_VERSION" major "$VERSION_FORMAT")" >> $GITHUB_OUTPUT
        echo "minor=$("$GITHUB_ACTION_PATH"/scripts/get-version-part.sh "$NEXT_VERSION" minor "$VERSION_FORMAT")" >> $GITHUB_OUTPUT
        echo "patch=$("$GITHUB_ACTION_PATH"/scripts/get-version-part.sh "$NEXT_VERSION" patch "$VERSION_FORMAT")" >> $GITHUB_OUTPUT

      env:
        NEXT_VERSION: ${{ steps.get-next-version.outputs.version }}
        VERSION_FORMAT: ${{ inputs.version-format }}

    - id: generate-release-notes
      if: ${{ steps.get-release-type.outputs.type != 'none' }}
      shell: bash
      env:
        VERSION_FORMAT: ${{ inputs.version-format }}

      run: |
        {
          echo "notes<<EOF"
          echo "$("$GITHUB_ACTION_PATH"/scripts/generate-release-notes.sh "$VERSION_FORMAT")"
          echo "EOF"
        } >> $GITHUB_OUTPUT
