name: GitHub Actions Release
on:
  push:
    branches: [ main ]

jobs:
  check:
    outputs:
      release-type: ${{ steps.lets-release.outputs.release-type }}
      next-version: ${{ steps.lets-release.outputs.next-version }}
      major: ${{ steps.lets-release.outputs.major }}
      release-notes-md: ${{ steps.lets-release.outputs.release-notes-md }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Let's release
        id: lets-release
        uses: TozyDev/lets-release@main

  release:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.release-type != 'none' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write release notes file
        run: echo -n "${{ needs.check.outputs.release-notes-md }}" > release-notes.md

      - name: Create release
        run: gh release create v${{ needs.check.outputs.next-version }} --title ${{ needs.check.outputs.next-version }} --notes-file _ << release-notes.md
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Tag major tag
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag -d v${{ needs.check.outputs.major }}
          git push origin :v${{ needs.check.outputs.major }}
          git tag -a v${{ needs.check.outputs.major }} -m "Release v${{ needs.check.outputs.major }}"
          git push origin v${{ needs.check.outputs.major }}
